# Path to the metagenomes files
metagenomes:
    # path to contigs reads folder
    reads_folder: "03-data/simulated_viral_metagenomes/ICTV"
    # identifier of the sample name in the reads files (e.g. _R if the file is named sample1_R1.fastq.gz)
    reads_identifier: "_"

# path to the result folder
output_folder: "05-results/taxonomic_annotation/simulated_reads/ICTV/"

# reference genome path
metabuli_db: "03-data/refdbs/metabuli_db/all"
# metabuli_db: "03-data/refdbs/metabuli_db/virus_only"

metabuli_db: "03-data/refdbs/ICTV/metabuli_ICTV"
