# Path to the metagenomes files
metagenomes:
    # path to contigs reads folder
    reads_folder: palaeofaeces_ecoevol/03-data/unaligned
    # identifier of the sample name in the reads files (e.g. _R if the file is named sample1_R1.fastq.gz)
    reads_identifier: "_"


# path to the result folder
output_folder: "03-data/fastqs/"
