# Path to the metagenomes files
metagenomes:
    # path to contigs reads folder
    # reads_folder: "paleofeces_assembly/03-data/fastqs"
    reads_folder: palaeofaeces_ecoevol/03-data/unaligned
    # identifier of the sample name in the reads files (e.g. _R if the file is named sample1_R1.fastq.gz)
    reads_identifier: "_"
    # path to contigs folder if you already done the assembly
    assemble_contigs: "palaeofaeces_ecoevol/04-analysis/metagenome_assembly/alignment"
    # Exention of the contig file (e.g. fasta)
    contigs_ext: ".fasta.gz"
    # contigs_ext: "-megahit.fasta.gz"

# path to the result folder
output_folder: "05-results/taxonomic_annotation/empirical_data_bwa"

# reference genome path
reference_genome: "05-results/taxonomic_annotation/empirical_data/top_viruses/viruses_decoy.fasta"


metadata: "03-data/refdbs/ICTV/ICTV_database/20240209/ICTV_metadata.tsv"

# sam2lca
# sam2lca_db: "03-data/refdbs/centrifuge_db/ICTV_decoy/sam2lca"
genomad_db: "03-data/refdbs/genomad_db_1.9"

checkv_db: "03-data/refdbs/checkv_db"
